"""Add obligation.ai_summary + ai_summary_at (cached AI 'why' explanation)

The Binder obligation detail can show an on-demand, plain-language explanation of an
obligation's status, generated by Claude and cached on the row so it is not regenerated on
every view. Two nullable columns hold the text and when it was written.

Postgres-only: local/dev SQLite builds its schema from create_all against the model, so the
add-column is skipped there. Guarded/idempotent.

Revision ID: 0017_obligation_ai_summary
Revises: 0016_binder_entity_group_len
Create Date: 2026-07-17
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "0017_obligation_ai_summary"
down_revision: Union[str, None] = "0016_binder_entity_group_len"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(bind, table: str, column: str) -> bool:
    insp = sa.inspect(bind)
    if table not in insp.get_table_names():
        return False
    return column in {c["name"] for c in insp.get_columns(table)}


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return
    if not _has_column(bind, "obligation", "ai_summary"):
        op.add_column("obligation", sa.Column("ai_summary", sa.Text(), nullable=True))
    if not _has_column(bind, "obligation", "ai_summary_at"):
        op.add_column("obligation", sa.Column("ai_summary_at", sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "sqlite":
        return
    if _has_column(bind, "obligation", "ai_summary_at"):
        op.drop_column("obligation", "ai_summary_at")
    if _has_column(bind, "obligation", "ai_summary"):
        op.drop_column("obligation", "ai_summary")
