/* Sample /api/v1/forum payload — dev fallback when VITE_API_BASE is unset.
   Mirrors the mockup's representative numbers so the view renders standalone. */
export default {
  status: "watch",
  watch: { count: 3, items: ["pastdue", "at_risk", "behind_pace"] },
  members_total: 70,
  roster: {
    total: 70, forum: 26, inner_circle: 44,
    primary: 62, add_on: 8, admin: 2,
    payment_mix: { monthly: 22, quarterly: 5, pif: 35, installments: 8 },
  },
  roster_detail: {
    summary: {
      total: 70, forum: 26, inner_circle: 44, primary: 62, add_on: 8, admin: 2,
      payment_mix: { monthly: 22, quarterly: 5, pif: 35, installments: 8 }, book: 1284000,
    },
    count: 72,
    rows: [
      { id: "r1", name: "Marcus Tran", seg: "F", kind: "primary", member_type: "Primary Member", status: "Active", payment: "pif", amount: 30000, last_payment: { date: "2024-02-10", amount: 30000 }, next_payment: { date: "2026-08-10", amount: 30000 }, enrolled: "2024-02-10", renews: "2026-08-10", brokerage: "eXp Realty", stripe_account: "Legacy SB Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r2", name: "Jordan Pierce", seg: "F", kind: "primary", member_type: "Primary Member", status: "Active", payment: "monthly", amount: 30000, last_payment: { date: "2026-06-15", amount: 2500 }, next_payment: { date: "2026-07-15", amount: 2500 }, enrolled: "2024-05-22", renews: "2026-08-22", brokerage: "Compass", stripe_account: "Forum Sub-Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r3", name: "Alicia Romero", seg: "F", kind: "primary", member_type: "Primary Member", status: "Active", payment: "pif", amount: 30000, last_payment: { date: "2024-09-01", amount: 30000 }, next_payment: { date: "2026-09-01", amount: 30000 }, enrolled: "2024-09-01", renews: "2026-09-01", brokerage: "Keller Williams", stripe_account: "Legacy SB Account", event: false, source_url: "https://app.gohighlevel.com/" },
      { id: "r4", name: "Sam Kessler", seg: "F", kind: "primary", member_type: "Primary Member", status: "Active", payment: "quarterly", amount: 30000, last_payment: { date: "2026-04-05", amount: 7500 }, next_payment: { date: "2026-07-05", amount: 7500 }, enrolled: "2025-01-14", renews: "2026-10-14", brokerage: "Real Broker", stripe_account: "Forum Sub-Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r5", name: "Priya Nair", seg: "F", kind: "add_on", member_type: "Add-On Member", status: "Active", payment: "pif", amount: 0, last_payment: null, next_payment: null, enrolled: "2025-01-14", renews: "2026-10-14", brokerage: "Real Broker", stripe_account: "Forum Sub-Account", event: false, source_url: "https://app.gohighlevel.com/" },
      { id: "r6", name: "Devon Walsh", seg: "F", kind: "primary", member_type: "Primary Member", status: "Active", payment: "monthly", amount: 27000, last_payment: { date: "2026-06-15", amount: 2250 }, next_payment: { date: "2026-07-15", amount: 2250 }, enrolled: "2024-11-30", renews: "2026-11-30", brokerage: null, stripe_account: "Legacy SB Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r7", name: "Hannah Brooks", seg: "F", kind: "primary", member_type: "Primary Member", status: "Active", payment: "pif", amount: 27000, last_payment: { date: "2024-03-18", amount: 27000 }, next_payment: { date: "2026-07-18", amount: 27000 }, enrolled: "2024-03-18", renews: "2026-07-18", brokerage: "The Agency", stripe_account: "Legacy SB Account", event: false, source_url: "https://app.gohighlevel.com/" },
      { id: "r8", name: "Carlos Mendez", seg: "F", kind: "primary", member_type: "Primary Member", status: "Active", payment: "pif", amount: 30000, last_payment: { date: "2023-12-05", amount: 30000 }, next_payment: { date: "2026-12-05", amount: 30000 }, enrolled: "2023-12-05", renews: "2026-12-05", brokerage: "eXp Realty", stripe_account: "Legacy SB Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r9", name: "Renee Fowler", seg: "F", kind: "primary", member_type: "Primary Member", status: "Active", payment: "installments", amount: 30000, last_payment: { date: "2026-05-20", amount: 10000 }, next_payment: { date: "2026-08-20", amount: 10000 }, enrolled: "2025-02-27", renews: "2026-09-27", brokerage: "RE/MAX", stripe_account: "Forum Sub-Account", event: false, source_url: "https://app.gohighlevel.com/" },
      { id: "r10", name: "Tobias Frey", seg: "F", kind: "primary", member_type: "Primary Member", status: "Active", payment: "pif", amount: 30000, last_payment: { date: "2024-06-11", amount: 30000 }, next_payment: { date: "2026-08-11", amount: 30000 }, enrolled: "2024-06-11", renews: "2026-08-11", brokerage: "Keller Williams", stripe_account: "Legacy SB Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r11", name: "Dana Whitfield", seg: "IC", kind: "primary", member_type: "Primary Member", status: "Active", payment: "monthly", amount: 6000, last_payment: { date: "2026-06-15", amount: 500 }, next_payment: { date: "2026-07-15", amount: 500 }, enrolled: "2024-08-19", renews: "2026-08-19", brokerage: "Compass", stripe_account: "Forum Sub-Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r12", name: "Chris Boone", seg: "IC", kind: "primary", member_type: "Primary Member", status: "Active", payment: "pif", amount: 6000, last_payment: { date: "2024-09-09", amount: 6000 }, next_payment: { date: "2026-09-09", amount: 6000 }, enrolled: "2024-09-09", renews: "2026-09-09", brokerage: null, stripe_account: "Legacy SB Account", event: false, source_url: "https://app.gohighlevel.com/" },
      { id: "r13", name: "Maya Iqbal", seg: "IC", kind: "primary", member_type: "Primary Member", status: "Active", payment: "pif", amount: 6000, last_payment: { date: "2025-03-03", amount: 6000 }, next_payment: { date: "2026-10-03", amount: 6000 }, enrolled: "2025-03-03", renews: "2026-10-03", brokerage: "eXp Realty", stripe_account: "Forum Sub-Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r14", name: "Grant Ellison", seg: "IC", kind: "add_on", member_type: "Add-On Member", status: "Active", payment: "pif", amount: 0, last_payment: null, next_payment: null, enrolled: "2025-03-03", renews: "2026-10-03", brokerage: "eXp Realty", stripe_account: "Forum Sub-Account", event: false, source_url: "https://app.gohighlevel.com/" },
      { id: "r15", name: "Olivia Park", seg: "IC", kind: "primary", member_type: "Primary Member", status: "Active", payment: "monthly", amount: 6000, last_payment: { date: "2026-06-15", amount: 500 }, next_payment: { date: "2026-07-15", amount: 500 }, enrolled: "2024-04-25", renews: "2026-07-25", brokerage: "Real Broker", stripe_account: "Legacy SB Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r16", name: "Nathan Cole", seg: "IC", kind: "primary", member_type: "Primary Member", status: "Active", payment: "installments", amount: 6000, last_payment: { date: "2026-05-20", amount: 2000 }, next_payment: { date: "2026-08-20", amount: 2000 }, enrolled: "2025-01-08", renews: "2026-11-08", brokerage: "The Agency", stripe_account: "Forum Sub-Account", event: false, source_url: "https://app.gohighlevel.com/" },
      { id: "r17", name: "Bianca Rossi", seg: "IC", kind: "primary", member_type: "Primary Member", status: "Active", payment: "pif", amount: 6000, last_payment: { date: "2024-07-16", amount: 6000 }, next_payment: { date: "2026-08-16", amount: 6000 }, enrolled: "2024-07-16", renews: "2026-08-16", brokerage: null, stripe_account: "Legacy SB Account", event: true, source_url: "https://app.gohighlevel.com/" },
      { id: "r18", name: "Wesley Hunt", seg: "IC", kind: "primary", member_type: "Primary Member", status: "Active", payment: "pif", amount: 6000, last_payment: { date: "2023-11-21", amount: 6000 }, next_payment: { date: "2026-12-21", amount: 6000 }, enrolled: "2023-11-21", renews: "2026-12-21", brokerage: "Keller Williams", stripe_account: "Legacy SB Account", event: false, source_url: "https://app.gohighlevel.com/" },
      { id: "r19", name: "Spring Ops", seg: "F", kind: "admin", member_type: "Admin", status: "Active", payment: null, amount: 0, last_payment: null, next_payment: null, enrolled: null, renews: null, brokerage: null, stripe_account: null, event: false, source_url: "https://app.gohighlevel.com/" },
      { id: "r20", name: "Taylor Reed", seg: "IC", kind: "admin", member_type: "Admin", status: "Active", payment: null, amount: 0, last_payment: null, next_payment: null, enrolled: null, renews: null, brokerage: null, stripe_account: null, event: false, source_url: "https://app.gohighlevel.com/" },
    ],
  },
  pl: null,
  kpis: [
    { key: "active_members", label: "Active Members", value: "70", sub: "Forum 26 · Inner Circle 44", drill: "active_members" },
    { key: "forum_arr", label: "Forum ARR", value: "$1.23M", sub: "47 memberships", drill: "forum_arr" },
    { key: "new_members", label: "New Members", value: "0", sub: "month to date" },
    { key: "renewals_due", label: "Renewals Due", value: "0", sub: "July", drill: "renewal_book" },
    { key: "registered", label: "Registered", value: "28", sub: "Park City, UT", drill: "registered" },
    { key: "mrr", label: "MRR", value: "$20K", sub: "monthly subscriptions", drill: "monthly" },
  ],
  deck: [
    { k: "pipeline", label: "Recruiting pipeline", hero: "138", hero_sub: "in the pipeline", salient: "15 in vip guest", tone: "good" },
    { k: "renewals", label: "Renewals · next 90 days", hero: "$300K", hero_sub: "12 renewals", salient: "Forum 8 · Inner Circle 4", tone: "good" },
    { k: "event", label: "Next event · Park City", hero: "75", hero_sub: "days out", salient: "42 unregistered · behind pace", tone: "watch" },
    { k: "revq", label: "Revenue quality", hero: "69%", hero_sub: "paid in full", salient: "2 past due · $4.4K", tone: "watch" },
  ],
  funnel: {
    stages: [
      { label: "Applied", v: 108 },
      { label: "Appointment", v: 15 },
      { label: "VIP Guest", v: 15 },
    ],
    footer: "54 more in nurture / unresponsive stages (not active deals)",
  },
  renewals: {
    rows: [
      { name: "Marcus Tran", seg: "F", month: "Aug", value: "$30K" },
      { name: "Jordan Pierce", seg: "F", month: "Aug", value: "$30K" },
      { name: "Dana Whitfield", seg: "IC", month: "Aug", value: "$18K" },
      { name: "Alicia Romero", seg: "F", month: "Sep", value: "$30K" },
      { name: "Chris Boone", seg: "IC", month: "Sep", value: "$18K" },
      { name: "Sam Kessler", seg: "F", month: "Oct", value: "$30K" },
    ],
    summary: {
      count: 12, value: "$300K",
      segments: { F: 8, IC: 4 },
      retention: null,
    },
  },
  event: {
    title: "The Forum · Q3 Immersion", where: "Park City, UT", when: "Sep 15–17",
    days_out: 75, registered: 28, members: 70, guests: 4, unregistered: 42,
    behind_pace: true, pace_note: "34 were registered at this point before Scottsdale Q2",
  },
  revq: {
    pif: { value: 828000, count: 33 },
    monthly: { value: 372000, count: 14, sub: "$31K MRR annualized" },
    past_due: { count: 2, value: "$4.4K" },
    bridge: [
      { label: "Jan 1", value: "$1.13M" },
      { label: "New", value: "+$158K" },
      { label: "Churned", value: "−$88K", soft: true },
      { label: "Today", value: "$1.2M", tot: true },
    ],
  },
  // Cash & Billing (GHL Payments, Stripe-fed) — cash-basis real-time truth.
  billing: {
    available: true, basis: "cash",
    span: { start: "2026-04-01", end: "2026-07-08" },
    net_cash: 131743, full_year: 263400, gross: 141993, refunded: 10250, txn_count: 39,
    failed_amount: 20000, failed_count: 2, past_due: 1, past_due_amount: 1800,
    monthly: [
      { month: "Jan", ym: "2026-01", actual: 0, projected: 0, net: 0, mtd: false, is_projected: false },
      { month: "Feb", ym: "2026-02", actual: 0, projected: 0, net: 0, mtd: false, is_projected: false },
      { month: "Mar", ym: "2026-03", actual: 0, projected: 0, net: 0, mtd: false, is_projected: false },
      { month: "Apr", ym: "2026-04", actual: 19500, projected: 0, net: 19500, mtd: false, is_projected: false },
      { month: "May", ym: "2026-05", actual: 84500, projected: 0, net: 84500, mtd: false, is_projected: false },
      { month: "Jun", ym: "2026-06", actual: 28600, projected: 0, net: 28600, mtd: false, is_projected: false },
      { month: "Jul", ym: "2026-07", actual: 9400, projected: 12400, net: 21800, mtd: true, is_projected: false },
      { month: "Aug", ym: "2026-08", actual: 0, projected: 21800, net: 21800, mtd: false, is_projected: true },
      { month: "Sep", ym: "2026-09", actual: 0, projected: 21800, net: 21800, mtd: false, is_projected: true },
      { month: "Oct", ym: "2026-10", actual: 0, projected: 21800, net: 21800, mtd: false, is_projected: true },
      { month: "Nov", ym: "2026-11", actual: 0, projected: 21800, net: 21800, mtd: false, is_projected: true },
      { month: "Dec", ym: "2026-12", actual: 0, projected: 21800, net: 21800, mtd: false, is_projected: true },
    ],
    forecast: { next_30: 21800, next_90: 62200, rest_of_year: 101000 },
    mrr: 20200, perpetual_count: 11,
    installments: [{ name: "Q3 Cohort · 3-pay", amount: 1600, total: 3, collected: 1, final_date: "2026-07-12" }],
    next30: {
      amount: 4800, charges: 3,
      schedule: [
        { date: "2026-07-12", amount: 1600, who: "Q3 Cohort" },
        { date: "2026-07-18", amount: 1650, who: "Marcus Tran" },
        { date: "2026-07-25", amount: 1550, who: "Dana Whitfield" },
      ],
    },
    arr_book: 1230000, run_rate: 242400,
    streams: [
      { key: "memberships", label: "Memberships", amount: 104000, pct: 79 },
      { key: "event_tickets", label: "Event tickets", amount: 14500, pct: 11 },
      { key: "sponsorships", label: "Sponsorships", amount: 10043, pct: 8 },
      { key: "invoices", label: "Invoices", amount: 3200, pct: 2 },
    ],
  },
};
